# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/menorzinho/GEANT4/Sim/symulacja_Bogus

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/menorzinho/GEANT4/Sim/symulacja_Bogus

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/menorzinho/GEANT4/Sim/symulacja_Bogus/CMakeFiles /home/menorzinho/GEANT4/Sim/symulacja_Bogus/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/menorzinho/GEANT4/Sim/symulacja_Bogus/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named bina_breakup2.11_dTarget

# Build rule for target.
bina_breakup2.11_dTarget: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 bina_breakup2.11_dTarget
.PHONY : bina_breakup2.11_dTarget

# fast build rule for target.
bina_breakup2.11_dTarget/fast:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/build
.PHONY : bina_breakup2.11_dTarget/fast

bina_breakup2.11_dTarget.o: bina_breakup2.11_dTarget.cc.o

.PHONY : bina_breakup2.11_dTarget.o

# target to build an object file
bina_breakup2.11_dTarget.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/bina_breakup2.11_dTarget.cc.o
.PHONY : bina_breakup2.11_dTarget.cc.o

bina_breakup2.11_dTarget.i: bina_breakup2.11_dTarget.cc.i

.PHONY : bina_breakup2.11_dTarget.i

# target to preprocess a source file
bina_breakup2.11_dTarget.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/bina_breakup2.11_dTarget.cc.i
.PHONY : bina_breakup2.11_dTarget.cc.i

bina_breakup2.11_dTarget.s: bina_breakup2.11_dTarget.cc.s

.PHONY : bina_breakup2.11_dTarget.s

# target to generate assembly for a file
bina_breakup2.11_dTarget.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/bina_breakup2.11_dTarget.cc.s
.PHONY : bina_breakup2.11_dTarget.cc.s

src/Bina_DetectorConstruction.o: src/Bina_DetectorConstruction.cc.o

.PHONY : src/Bina_DetectorConstruction.o

# target to build an object file
src/Bina_DetectorConstruction.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorConstruction.cc.o
.PHONY : src/Bina_DetectorConstruction.cc.o

src/Bina_DetectorConstruction.i: src/Bina_DetectorConstruction.cc.i

.PHONY : src/Bina_DetectorConstruction.i

# target to preprocess a source file
src/Bina_DetectorConstruction.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorConstruction.cc.i
.PHONY : src/Bina_DetectorConstruction.cc.i

src/Bina_DetectorConstruction.s: src/Bina_DetectorConstruction.cc.s

.PHONY : src/Bina_DetectorConstruction.s

# target to generate assembly for a file
src/Bina_DetectorConstruction.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorConstruction.cc.s
.PHONY : src/Bina_DetectorConstruction.cc.s

src/Bina_DetectorMessenger.o: src/Bina_DetectorMessenger.cc.o

.PHONY : src/Bina_DetectorMessenger.o

# target to build an object file
src/Bina_DetectorMessenger.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorMessenger.cc.o
.PHONY : src/Bina_DetectorMessenger.cc.o

src/Bina_DetectorMessenger.i: src/Bina_DetectorMessenger.cc.i

.PHONY : src/Bina_DetectorMessenger.i

# target to preprocess a source file
src/Bina_DetectorMessenger.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorMessenger.cc.i
.PHONY : src/Bina_DetectorMessenger.cc.i

src/Bina_DetectorMessenger.s: src/Bina_DetectorMessenger.cc.s

.PHONY : src/Bina_DetectorMessenger.s

# target to generate assembly for a file
src/Bina_DetectorMessenger.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_DetectorMessenger.cc.s
.PHONY : src/Bina_DetectorMessenger.cc.s

src/Bina_EventAction.o: src/Bina_EventAction.cc.o

.PHONY : src/Bina_EventAction.o

# target to build an object file
src/Bina_EventAction.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_EventAction.cc.o
.PHONY : src/Bina_EventAction.cc.o

src/Bina_EventAction.i: src/Bina_EventAction.cc.i

.PHONY : src/Bina_EventAction.i

# target to preprocess a source file
src/Bina_EventAction.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_EventAction.cc.i
.PHONY : src/Bina_EventAction.cc.i

src/Bina_EventAction.s: src/Bina_EventAction.cc.s

.PHONY : src/Bina_EventAction.s

# target to generate assembly for a file
src/Bina_EventAction.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_EventAction.cc.s
.PHONY : src/Bina_EventAction.cc.s

src/Bina_Graniastoslupy.o: src/Bina_Graniastoslupy.cc.o

.PHONY : src/Bina_Graniastoslupy.o

# target to build an object file
src/Bina_Graniastoslupy.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Graniastoslupy.cc.o
.PHONY : src/Bina_Graniastoslupy.cc.o

src/Bina_Graniastoslupy.i: src/Bina_Graniastoslupy.cc.i

.PHONY : src/Bina_Graniastoslupy.i

# target to preprocess a source file
src/Bina_Graniastoslupy.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Graniastoslupy.cc.i
.PHONY : src/Bina_Graniastoslupy.cc.i

src/Bina_Graniastoslupy.s: src/Bina_Graniastoslupy.cc.s

.PHONY : src/Bina_Graniastoslupy.s

# target to generate assembly for a file
src/Bina_Graniastoslupy.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Graniastoslupy.cc.s
.PHONY : src/Bina_Graniastoslupy.cc.s

src/Bina_Obroty.o: src/Bina_Obroty.cc.o

.PHONY : src/Bina_Obroty.o

# target to build an object file
src/Bina_Obroty.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Obroty.cc.o
.PHONY : src/Bina_Obroty.cc.o

src/Bina_Obroty.i: src/Bina_Obroty.cc.i

.PHONY : src/Bina_Obroty.i

# target to preprocess a source file
src/Bina_Obroty.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Obroty.cc.i
.PHONY : src/Bina_Obroty.cc.i

src/Bina_Obroty.s: src/Bina_Obroty.cc.s

.PHONY : src/Bina_Obroty.s

# target to generate assembly for a file
src/Bina_Obroty.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_Obroty.cc.s
.PHONY : src/Bina_Obroty.cc.s

src/Bina_PhysicsList.o: src/Bina_PhysicsList.cc.o

.PHONY : src/Bina_PhysicsList.o

# target to build an object file
src/Bina_PhysicsList.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsList.cc.o
.PHONY : src/Bina_PhysicsList.cc.o

src/Bina_PhysicsList.i: src/Bina_PhysicsList.cc.i

.PHONY : src/Bina_PhysicsList.i

# target to preprocess a source file
src/Bina_PhysicsList.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsList.cc.i
.PHONY : src/Bina_PhysicsList.cc.i

src/Bina_PhysicsList.s: src/Bina_PhysicsList.cc.s

.PHONY : src/Bina_PhysicsList.s

# target to generate assembly for a file
src/Bina_PhysicsList.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsList.cc.s
.PHONY : src/Bina_PhysicsList.cc.s

src/Bina_PhysicsMessenger.o: src/Bina_PhysicsMessenger.cc.o

.PHONY : src/Bina_PhysicsMessenger.o

# target to build an object file
src/Bina_PhysicsMessenger.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsMessenger.cc.o
.PHONY : src/Bina_PhysicsMessenger.cc.o

src/Bina_PhysicsMessenger.i: src/Bina_PhysicsMessenger.cc.i

.PHONY : src/Bina_PhysicsMessenger.i

# target to preprocess a source file
src/Bina_PhysicsMessenger.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsMessenger.cc.i
.PHONY : src/Bina_PhysicsMessenger.cc.i

src/Bina_PhysicsMessenger.s: src/Bina_PhysicsMessenger.cc.s

.PHONY : src/Bina_PhysicsMessenger.s

# target to generate assembly for a file
src/Bina_PhysicsMessenger.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PhysicsMessenger.cc.s
.PHONY : src/Bina_PhysicsMessenger.cc.s

src/Bina_PrimaryGeneratorAction.o: src/Bina_PrimaryGeneratorAction.cc.o

.PHONY : src/Bina_PrimaryGeneratorAction.o

# target to build an object file
src/Bina_PrimaryGeneratorAction.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PrimaryGeneratorAction.cc.o
.PHONY : src/Bina_PrimaryGeneratorAction.cc.o

src/Bina_PrimaryGeneratorAction.i: src/Bina_PrimaryGeneratorAction.cc.i

.PHONY : src/Bina_PrimaryGeneratorAction.i

# target to preprocess a source file
src/Bina_PrimaryGeneratorAction.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PrimaryGeneratorAction.cc.i
.PHONY : src/Bina_PrimaryGeneratorAction.cc.i

src/Bina_PrimaryGeneratorAction.s: src/Bina_PrimaryGeneratorAction.cc.s

.PHONY : src/Bina_PrimaryGeneratorAction.s

# target to generate assembly for a file
src/Bina_PrimaryGeneratorAction.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_PrimaryGeneratorAction.cc.s
.PHONY : src/Bina_PrimaryGeneratorAction.cc.s

src/Bina_SteppingAction.o: src/Bina_SteppingAction.cc.o

.PHONY : src/Bina_SteppingAction.o

# target to build an object file
src/Bina_SteppingAction.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_SteppingAction.cc.o
.PHONY : src/Bina_SteppingAction.cc.o

src/Bina_SteppingAction.i: src/Bina_SteppingAction.cc.i

.PHONY : src/Bina_SteppingAction.i

# target to preprocess a source file
src/Bina_SteppingAction.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_SteppingAction.cc.i
.PHONY : src/Bina_SteppingAction.cc.i

src/Bina_SteppingAction.s: src/Bina_SteppingAction.cc.s

.PHONY : src/Bina_SteppingAction.s

# target to generate assembly for a file
src/Bina_SteppingAction.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_SteppingAction.cc.s
.PHONY : src/Bina_SteppingAction.cc.s

src/Bina_VisManager.o: src/Bina_VisManager.cc.o

.PHONY : src/Bina_VisManager.o

# target to build an object file
src/Bina_VisManager.cc.o:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_VisManager.cc.o
.PHONY : src/Bina_VisManager.cc.o

src/Bina_VisManager.i: src/Bina_VisManager.cc.i

.PHONY : src/Bina_VisManager.i

# target to preprocess a source file
src/Bina_VisManager.cc.i:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_VisManager.cc.i
.PHONY : src/Bina_VisManager.cc.i

src/Bina_VisManager.s: src/Bina_VisManager.cc.s

.PHONY : src/Bina_VisManager.s

# target to generate assembly for a file
src/Bina_VisManager.cc.s:
	$(MAKE) -f CMakeFiles/bina_breakup2.11_dTarget.dir/build.make CMakeFiles/bina_breakup2.11_dTarget.dir/src/Bina_VisManager.cc.s
.PHONY : src/Bina_VisManager.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... bina_breakup2.11_dTarget"
	@echo "... install"
	@echo "... bina_breakup2.11_dTarget.o"
	@echo "... bina_breakup2.11_dTarget.i"
	@echo "... bina_breakup2.11_dTarget.s"
	@echo "... src/Bina_DetectorConstruction.o"
	@echo "... src/Bina_DetectorConstruction.i"
	@echo "... src/Bina_DetectorConstruction.s"
	@echo "... src/Bina_DetectorMessenger.o"
	@echo "... src/Bina_DetectorMessenger.i"
	@echo "... src/Bina_DetectorMessenger.s"
	@echo "... src/Bina_EventAction.o"
	@echo "... src/Bina_EventAction.i"
	@echo "... src/Bina_EventAction.s"
	@echo "... src/Bina_Graniastoslupy.o"
	@echo "... src/Bina_Graniastoslupy.i"
	@echo "... src/Bina_Graniastoslupy.s"
	@echo "... src/Bina_Obroty.o"
	@echo "... src/Bina_Obroty.i"
	@echo "... src/Bina_Obroty.s"
	@echo "... src/Bina_PhysicsList.o"
	@echo "... src/Bina_PhysicsList.i"
	@echo "... src/Bina_PhysicsList.s"
	@echo "... src/Bina_PhysicsMessenger.o"
	@echo "... src/Bina_PhysicsMessenger.i"
	@echo "... src/Bina_PhysicsMessenger.s"
	@echo "... src/Bina_PrimaryGeneratorAction.o"
	@echo "... src/Bina_PrimaryGeneratorAction.i"
	@echo "... src/Bina_PrimaryGeneratorAction.s"
	@echo "... src/Bina_SteppingAction.o"
	@echo "... src/Bina_SteppingAction.i"
	@echo "... src/Bina_SteppingAction.s"
	@echo "... src/Bina_VisManager.o"
	@echo "... src/Bina_VisManager.i"
	@echo "... src/Bina_VisManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

